name: Basic Rust CI
on: [push]

jobs:
  BasicRustTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Repository
        uses: actions/checkout@v3
      - name: Install Cargo Format Nightly
        uses: rustup component add rustfmt --toolchain nightly
      - name: Cargo test all
        run: cargo test --all --verbose
      - name: Cargo Format Lint Check
        run: cargo fmt --all --check --verbose
      - name: Cargo Build Release
        run: cargo b --release --verbose