name: Basic Rust CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  BasicRustTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Repository
        uses: actions/checkout@v3
      - name: Cargo test all
        run: cargo test --all --verbose
      - name: Cargo Build Release
        run: cargo b --release --verbose
      - name: Cargo Format Lint Check
        run: cargo fmt --all --check --verbose
      - name: Cargo Clippy Pedant
        run: cargo clippy